spring:
#  main:
#    allow-bean-definition-overriding: true
  cloud:
    stream:
      function:
        definition: produceCreatedUser
        bindings:
          produceCreatedUser-out-0: 'produce-created-user'
      bindings:
        produce-created-user:
          destination: 'user-topic'
      kafka:
        binder:
          brokers: 'localhost:9092'
          auto-create-topics: false
          auto-add-partitions: false